
package poli;

import java.awt.Color;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abraham
 */
public class datalles_incidentes extends javax.swing.JFrame {

    DefaultTableModel model;
    Statement sent;
    CallableStatement cst;
    Connection conect;
    
    public datalles_incidentes() {
        initComponents();
        setLocationRelativeTo(null);
        final Color alphaZero = new Color(0, true);
        cargar("");
        
        jScrollPane1.setBorder(null);
        jScrollPane5.setBorder(null);
        
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.getViewport().setBackground(alphaZero);
        jScrollPane5.getViewport().setOpaque(false);
        jScrollPane5.getViewport().setBackground(alphaZero);
        
        nombres.setBackground(new Color(0, 0, 0, 40));
        apellidos.setBackground(new Color(0, 0, 0, 40));
        cedula.setBackground(new Color(0, 0, 0, 40));
        fecha.setBackground(new Color(0, 0, 0, 40));
        direccion.setBackground(new Color(0, 0, 0, 40));
        busca_incidente.setBackground(new Color(0, 0, 0, 40));
        detalles_in.setBackground(new Color(0, 0, 0, 40));
        idfuncionario.setBackground(new Color(0, 0, 0, 40));
    }
    
    
    void cargar(String valor) {
        try {
            String[] titulos = {"Id", "Nombres", "Apellidos", "Cedula", "idfuncionario"};
            String[] registros = new String[5];
            String sql = "SELECT * FROM registro_personal_incidentes where Cedula LIKE '%" + valor + "%' ";
            model = new DefaultTableModel(null, titulos);
            sent = cn.createStatement();
            ResultSet rs = sent.executeQuery(sql);
            while (rs.next()) {
                registros[0] = rs.getString("Id");
                registros[1] = rs.getString("Nombres");
                registros[2] = rs.getString("Apellidos");
                registros[3] = rs.getString("Cedula");
                registros[4] = rs.getString("idfuncionario");

                model.addRow(registros);
            }
            jTable1.setModel(model);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escudo = new javax.swing.JLabel();
        nombres = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        apellidos = new javax.swing.JTextField();
        cedula = new javax.swing.JTextField();
        fecha = new javax.swing.JTextField();
        idfuncionario = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        detalles_in = new javax.swing.JTextArea();
        busca_incidente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        atras = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 500));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        escudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/es3.png"))); // NOI18N
        getContentPane().add(escudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, 140, 270));

        nombres.setEditable(false);
        nombres.setForeground(new java.awt.Color(255, 255, 255));
        nombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombresKeyTyped(evt);
            }
        });
        getContentPane().add(nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 310, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("NOMBRES:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("APELLIDOS:");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("CÉDULA:");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("DIRECCIÓN:");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FECHA:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("USUARIO:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, -1, -1));

        direccion.setEditable(false);
        direccion.setForeground(new java.awt.Color(255, 255, 255));
        direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                direccionKeyTyped(evt);
            }
        });
        getContentPane().add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 510, -1));

        apellidos.setEditable(false);
        apellidos.setForeground(new java.awt.Color(255, 255, 255));
        apellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apellidosKeyTyped(evt);
            }
        });
        getContentPane().add(apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 310, -1));

        cedula.setEditable(false);
        cedula.setForeground(new java.awt.Color(255, 255, 255));
        cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cedulaKeyTyped(evt);
            }
        });
        getContentPane().add(cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 130, -1));

        fecha.setEditable(false);
        fecha.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 110, -1));

        idfuncionario.setEditable(false);
        idfuncionario.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(idfuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, 110, -1));

        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "DATOS PERSONALES: ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 810, 120));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 810, 150));

        jScrollPane5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        detalles_in.setEditable(false);
        detalles_in.setBackground(new java.awt.Color(153, 153, 153));
        detalles_in.setColumns(20);
        detalles_in.setForeground(new java.awt.Color(255, 255, 255));
        detalles_in.setLineWrap(true);
        detalles_in.setRows(5);
        detalles_in.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        detalles_in.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        detalles_in.setOpaque(false);
        jScrollPane5.setViewportView(detalles_in);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 790, 110));

        busca_incidente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        busca_incidente.setForeground(new java.awt.Color(255, 255, 255));
        busca_incidente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                busca_incidenteKeyReleased(evt);
            }
        });
        getContentPane().add(busca_incidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 320, 120, -1));

        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "BUSCADOR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 300, 140, 60));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "DETALLES DEL INCIDENTE: ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 810, 150));

        atras.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        atras.setForeground(new java.awt.Color(255, 255, 255));
        atras.setText("< ATRAS");
        atras.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        atras.setContentAreaFilled(false);
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        getContentPane().add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 100, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombresKeyTyped
                // TODO add your handling code here:
    }//GEN-LAST:event_nombresKeyTyped

    private void direccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_direccionKeyTyped
                // TODO add your handling code here:
    }//GEN-LAST:event_direccionKeyTyped

    private void apellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidosKeyTyped
                // TODO add your handling code here:
    }//GEN-LAST:event_apellidosKeyTyped

    private void cedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cedulaKeyTyped
                // TODO add your handling code here:
    }//GEN-LAST:event_cedulaKeyTyped

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
if (evt.getButton() == 1) {
            int pst = jTable1.getSelectedRow();
            try {
                String sql = "SELECT * FROM registro_policial_incidentes where Id= " + jTable1.getValueAt(pst, 0).toString();
                sent = cn.createStatement();
                ResultSet rs = sent.executeQuery(sql);
                rs.next();
                nombres.setText(rs.getString("Nombres"));
                apellidos.setText(rs.getString("Apellidos"));
                cedula.setText(rs.getString("Cedula"));
                direccion.setText(rs.getString("Direccion"));
                fecha.setText(rs.getString("Fecha"));
                detalles_in.setText(rs.getString("Detalles"));
                idfuncionario.setText(rs.getString("idfuncionario"));

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
        busca_incidente.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void busca_incidenteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busca_incidenteKeyReleased
    cargar(busca_incidente.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_busca_incidenteKeyReleased

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
    
    detalles.jButton4.setEnabled(true);
    dispose();// TODO add your handling code here:
    }//GEN-LAST:event_atrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datalles_incidentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datalles_incidentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datalles_incidentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datalles_incidentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new datalles_incidentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidos;
    private javax.swing.JButton atras;
    private javax.swing.JTextField busca_incidente;
    private javax.swing.JTextField cedula;
    private javax.swing.JTextArea detalles_in;
    private javax.swing.JTextField direccion;
    private javax.swing.JLabel escudo;
    private javax.swing.JTextField fecha;
    private javax.swing.JLabel fondo;
    private javax.swing.JTextField idfuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nombres;
    // End of variables declaration//GEN-END:variables
conectar cc = new conectar();
    Connection cn = cc.conexion();
}

